// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CPBLDemo.Models;

public partial class Team
{
    public int TeamId { get; set; }

    public string TeamName { get; set; }

    public virtual ICollection<PlayerList> PlayerList { get; set; } = new List<PlayerList>();
}