// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CPBLDemo.Models;

public partial class PlayerList
{
    public int Id { get; set; }

    public int Number { get; set; }

    public string Position { get; set; }

    public string Team { get; set; }

    public string Name { get; set; }

    public decimal Height { get; set; }

    public decimal Weight { get; set; }

    public DateTime FirstDate { get; set; }

    public DateTime CreatedTime { get; set; }
}